# FROM python:latest
# WORKDIR /app
#
# ENV PYTHONPATH="${PYTHONPATH}:/app"
#
# COPY requirements.txt ./
# RUN pip install -r requirements.txt
# COPY . /app/
# CMD ["streamlit", "run", "chat/chat.py", "--server.port=8501", "--server.address=0.0.0.0"]
#


FROM python:latest
WORKDIR /app

ENV PYTHONPATH="${PYTHONPATH}:/app"
ENV PYTHONUNBUFFERED=1

COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY . /app/
CMD ["streamlit", "run", "chat/chat.py", "--server.port=8501", "--server.address=0.0.0.0"]
