[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
embeddings_onchain = "A1g3ToDasaBD2Xc11rhALercNtNeaWmTS1VxCqhQ6Daa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
